id: water_alert_water_heater
alias: Water Alert (Water Heater)
mode: single
trigger:
- platform: state
  entity_id: sensor.water_sensor_alarm_water_2
  from: 'Clear'
action:
- service: notify.notify
  data:
    data:
      title: Water Alert!
      message: Water Detected at Water Heater
      push:
        sound:
          critical: 1
          name: default
          volume: 1
