---
id: garage_notify_on_close
alias: Garage - Notify on Close
trigger:
- entity_id: cover.garage
  platform: state
  from:
  - open
  - closing
  to: closed
action:
- service: notify.notify
  data:
    message: Garage Door Closed
    title: Garage
