id: blink_update_stills
alias: Update Blink Stills
mode: single
trigger:
- platform: time
  at: '07:00:00'
- platform: time
  at: '14:00:00'
- platform: time
  at: '20:00:00'
action:
- service: script.refresh_blink_images
  data: {}
